add server echomc
CheatBreakerNet/Client-API pull request #3
Opened 2023-05-17 20:29 UTC by itzCrih

### General:
* [ ] The pull request title is descriptive. *(ex. `Added GoldenPvP Network`, not `Updated metadata.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] Folder with appropriate name has been created / updated (must not include any non-alpha characters or whitespace).
* [ ] No changes were made to the file's formatting (4 spaces per tab).
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id (check if there is an existing folder).
* [ ] My field values match your requirements.
* You can view our patterns here: [metadata.schema.json](https://github.com/CheatBreakerNet/Client-API/blob/master/mappings/metadata.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string, which should match the folder name *(ex. `goldenpvpnetwork`)*
  - [ ] `name`: a string *(ex. `GoldenPvP Network`)*
  - [ ] `description`: hook between 16 and 40 characters *(ex. `We're the home of classic PvP gamemodes`)* 
  - [ ] `addresses`: an array with lowercase strings *(ex. `["goldenpvp.net", "routing.center"]`)*
    - You do not need to specify subdomains, CheatBreaker services automatically detect them.
  - [ ] `primaryAddress`: the primary address that people connect to with (please include the subdomain if required) *(ex. `mc.goldenpvp.net`)*
  - [ ] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.7.*", "1.8.9"]` - Must be versions or subversions supported by CheatBreaker)*
  - [ ] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.7.10` - Must be a subversion supported by CheatBreaker)*
  - [ ] `primaryColor`: a hexademical color code that primarily distinguishes the server *(ex. `#00FFFF`)* 
  - [ ] `secondaryColor`: a hexademical color code that accompanies the `primaryColor` of the server *(ex. `#FF0000`)*
  - [ ] `primaryRegion`: the primary region where your server operates in *(ex. `EU`)*
  - [ ] `regions`: a list of regions where you have servers located that service your players *(ex. `["EU", "NA", "AS"]`)*
  - [ ] `gameTypes`: a list of games that describe the content on your server, must be a max of 3 listed *(ez. `["PVP", "UHC", "HCF"]`)*
  - [ ] (optional) `website`: url of server website, must include URL schema (http:// or https://) *(ex. `https://www.goldenpvp.net`)*
  - [ ] (optional) `store`: url of server store, must include URL schema (http:// or https://) *(ex. `https://store.goldenpvp.net`)*

### Socials
* [ ] (optional) `twitter`: username of twitter account without the @ *(ex. GoldenPvPNet)*
* [ ] (optional) `discord`: invite link to discord *(ex. https://discord.com/invite/3EAzBxf)*
* [ ] (optional) `youtube`: slug or username of youtube channel *(ex. GoldenPvP)*
* [ ] (optional) `instagram`: username of instagram account *(ex. GoldenPvPNet)*
* [ ] (optional) `twitch`: username of twitch account *(ex. GoldenPvPNet)*
* [ ] (optional) `telegram`: slug of telegram group *(ex. GoldenPvP-Network)*
* [ ] (optional) `reddit`: slug of subdreddit wtih 'r/' *(ex. GoldenPvP)*
* [ ] (optional) `tiktok`: username of tiktok account *(ex. GoldenPvP)*
* [ ] (optional) `facebook`: slug of facebook page *(ex. GoldenPvP)*

### Media:
#### Icon
* [ ] My icon is a `png` file.
* [ ] I have uploaded my icon to my server folder *(ex. `goldenpvpnetwork`)* and named it `icon.png`.
* [ ] My icon has a transparent background and is square (1:1 aspect ratio).
* [ ] My icon is `64` pixels in width and height.
* [ ] My icon is my own property and complies with relevant copyright/privacy laws.

#### Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `goldenpvpnetwork`)* and named it `logo.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is `108` pixels in width and height.
* [ ] My logo is my own property and complies with relevant copyright/privacy laws.

#### Discord Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `goldenpvpnetwork`)* and named it `discord.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is between `512` and `1024` pixels in width and height.
* [ ] My logo is my own property and complies with relevant copyright/privacy laws.

#### Primary Background (Only required for partnered servers)
* [ ] My primary background is a `png` file.
* [ ] I have uploaded my primary background to my server folder *(ex. `goldenpvpnetwork`)* and named it `primarybackground.png`.
* [ ] My primary background is `774` pixels in width and `363` pixels in height.
* [ ] My primary background contains relevant content pertaining to the server, is my own property, and complies with relevant copyright/privacy laws.
* [ ] My primary background doesn't contain any markings, text, or logos (unless part of a build).

#### Secondary Background (Only required for partnered servers)
* [ ] My secondary background is a `png` file.
* [ ] I have uploaded my secondary background to my server folder *(ex. `goldenpvpnetwork`)* and named it `secondarybackground.png`.
* [ ] My secondary background is `447` pixels in width and `172` pixels in height.
* [ ] My secondary background contains relevant content pertaining to the server, is my own property, and complies with relevant copyright/privacy laws.
* [ ] My secondary background doesn't contain any markings, text, or logos (unless part of a build).

2023-05-17 21:02 UTC, ShonP40 commented
Please go over your PR and check all the relevant boxes above.
This should’ve been done before you submitted the PR.

2023-05-17 21:09 UTC, itzCrih commented
i checked all the squares

2023-05-17 22:00 UTC, ShonP40 requested changes

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/discord.png
This logo has some artifacts on it, do you have one that looks better?

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/metadata.json
> +        "play.echomc.it"
As stated in the readme file, you don’t need to specify subdomains here

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/metadata.json
> +    "website": "https://echomc.it/",
This website doesn’t seem to exist.
Remove this line if you don’t have a website.

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/metadata.json
> +        "twitter": "EchoMC",
This Twitter account does not exist.
Remove this line if you don’t have a Twitter account for the server

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/metadata.json
> +        "reddit": "EchoMC"
Judging by the fact that this Reddit account is 11 years old, I’m pretty sure that it’s not related to your server, so remove this line

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/discord.png
Also, as stated in the readme, this image should be 512x512 or higher.
Yours is 256x256

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/logo.png
As stated in the readme, this image should be 108x108
Yours is 1080x1080

2023-05-17 22:00 UTC, ShonP40 commented on mappings/servers/echomc/metadata.json
> +    "description": "The best kitpvp server in italy",
Names should start with a capital letter, so instead of `italy`, type `Italy` + it’s supposed to be `KitPvP`, not `kitpvp`

2023-05-17 22:01 UTC, ShonP40 commented
> i checked all the squares

You checked boxes related to server backgrounds while not providing any, please uncheck those.

2023-05-17 22:22 UTC, Tellinq commented
There's a saying "Don't say that you did something, prove or show it." Make sure that you follow that. We can't accept your request until you properly prove that you did.

2023-05-18 05:28 UTC, itzCrih commented
I solved all the problems, and the site is working but needs www on it, sorry my fault

2023-05-18 06:44 UTC, ShonP40 approved these changes

2023-05-18 06:51 UTC, ShonP40 commented
Looks like GitHub actions decided to bug out again
So going to wait until it starts working again before merging

2023-05-22 21:23 UTC, ShonP40 approved these changes

2023-05-22 21:24 UTC, merged