Add LandsMC
CheatBreakerNet/Client-API pull request #81
Opened 2024-03-15 09:28 UTC by Gustvst

Add LandsMC

### General:
* [ ] The pull request title is descriptive. *(ex. `Added GoldenPvP Network`, not `Updated metadata.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] Folder with appropriate name has been created / updated (must not include any non-alpha characters or whitespace).
* [ ] No changes were made to the file's formatting (4 spaces per tab).
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id (check if there is an existing folder).
* [ ] My field values match your requirements.
* You can view our patterns here: [metadata.schema.json](https://github.com/CheatBreakerNet/Client-API/blob/master/mappings/metadata.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string, which should match the folder name *(ex. `goldenpvpnetwork`)*
  - [ ] `name`: a string *(ex. `GoldenPvP Network`)*
  - [ ] `description`: hook between 16 and 40 characters *(ex. `We're the home of classic PvP gamemodes`)* 
  - [ ] `addresses`: an array with lowercase strings *(ex. `["goldenpvp.net", "routing.center"]`)*
    - You do not need to specify subdomains, CheatBreaker services automatically detect them.
  - [ ] `primaryAddress`: the primary address that people connect to with (please include the subdomain if required) *(ex. `mc.goldenpvp.net`)*
  - [ ] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.7.*", "1.8.9"]` - Must be versions or subversions supported by CheatBreaker)*
  - [ ] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.7.10` - Must be a subversion supported by CheatBreaker)*
  - [ ] `primaryColor`: a hexademical color code that primarily distinguishes the server *(ex. `#00FFFF`)* 
  - [ ] `secondaryColor`: a hexademical color code that accompanies the `primaryColor` of the server *(ex. `#FF0000`)*
  - [ ] `primaryRegion`: the primary region where your server operates in *(ex. `EU`)*
  - [ ] `regions`: a list of regions where you have servers located that service your players *(ex. `["EU", "NA", "AS"]`)*
  - [ ] `gameTypes`: a list of games that describe the content on your server, must be a max of 3 listed *(ez. `["PVP", "UHC", "HCF"]`)*
  - [ ] (optional) `website`: url of server website, must include URL schema (http:// or https://) *(ex. `https://www.goldenpvp.net`)*
  - [ ] (optional) `store`: url of server store, must include URL schema (http:// or https://) *(ex. `https://store.goldenpvp.net`)*

### Socials
* [ ] (optional) `twitter`: username of twitter account without the @ *(ex. GoldenPvPNet)*
* [ ] (optional) `discord`: invite link to discord *(ex. https://discord.com/invite/3EAzBxf)*
* [ ] (optional) `youtube`: slug or username of youtube channel *(ex. GoldenPvP)*
* [ ] (optional) `instagram`: username of instagram account *(ex. GoldenPvPNet)*
* [ ] (optional) `twitch`: username of twitch account *(ex. GoldenPvPNet)*
* [ ] (optional) `telegram`: slug of telegram group *(ex. GoldenPvP-Network)*
* [ ] (optional) `reddit`: slug of subdreddit wtih 'r/' *(ex. GoldenPvP)*
* [ ] (optional) `tiktok`: username of tiktok account *(ex. GoldenPvP)*
* [ ] (optional) `facebook`: slug of facebook page *(ex. GoldenPvP)*

### Media:
#### Icon
* [ ] My icon is a `png` file.
* [ ] I have uploaded my icon to my server folder *(ex. `goldenpvpnetwork`)* and named it `icon.png`.
* [ ] My icon has a transparent background and is square (1:1 aspect ratio).
* [ ] My icon is `64` pixels in width and height.
* [ ] My icon is my own/the server's property and complies with relevant copyright/privacy laws.

#### Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `goldenpvpnetwork`)* and named it `logo.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is `108` pixels in width and height.
* [ ] My logo is my own/the server's property and complies with relevant copyright/privacy laws.

#### Discord Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `goldenpvpnetwork`)* and named it `discord.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is between `512` and `1024` pixels in width and height.
* [ ] My logo is my own/the server's property and complies with relevant copyright/privacy laws.

#### Primary Background (Only required for partnered servers)
* [ ] My primary background is a `png` file.
* [ ] I have uploaded my primary background to my server folder *(ex. `goldenpvpnetwork`)* and named it `primarybackground.png`.
* [ ] My primary background is `774` pixels in width and `363` pixels in height.
* [ ] My primary background contains relevant content pertaining to the server, is my own/the server's property, and complies with relevant copyright/privacy laws.
* [ ] My primary background doesn't contain any markings, text, or logos (unless part of a build).

#### Secondary Background (Only required for partnered servers)
* [ ] My secondary background is a `png` file.
* [ ] I have uploaded my secondary background to my server folder *(ex. `goldenpvpnetwork`)* and named it `secondarybackground.png`.
* [ ] My secondary background is `447` pixels in width and `172` pixels in height.
* [ ] My secondary background contains relevant content pertaining to the server, is my own/the server's property, and complies with relevant copyright/privacy laws.
* [ ] My secondary background doesn't contain any markings, text, or logos (unless part of a build).

2024-03-16 00:52 UTC, Tellinq commented
Please use the checklist to your advantage. You have the following requirements not met:

- You have syntax errors
- Your server addresses MUST be lowercase for consistency
- Language is not in the proper case
- Region MUST be uppercase
- Please remove the erratic space in Regions
- Do not specify a field if there are none that supply it. You have set twitter to `none`, which would get detected by our metadata parser. If you do not have a Twitter social account, do not have a field for it
- ALL the images you supplied are in the INCORRECT resolution.
- You are missing Icon

If you have any further questions, let me know. I will take a look again when you make your next commit (hopefully with all these issues fixed)

2024-03-16 01:02 UTC, Tellinq requested changes

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +        "Stydismc.com"
Make sure this is always lowercase.

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +    ],
For languages that include a `-`, the correct way to put this is to have the last end be fully uppercase. In your case: pt-BR and pt-PT

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +    "primaryRegion": "sa",
Needs to be fully uppercase: `SA`

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +
Erratic space. Please remove

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +    "website": "https://landsmc.com/,
You have a syntax error here. Please make sure to have end quotes.

2024-03-16 01:02 UTC, Tellinq commented on metadata.json
> +        "twitter": "none",
Don't include this. If you do not have a Twitter account, don't include it in the metadata.

2024-03-17 16:29 UTC, Tellinq requested changes

2024-03-17 16:29 UTC, Tellinq commented on discord.png
You sure you really want to squish the logo now? All that was needed was a crop

this applies to the rest of your images

since your image was originally 1280x720, what you could have done was take that 1280x720 image and **crop** it to 720x720. That would have kept our requirements and kept a high resolution

2024-03-17 16:31 UTC, Tellinq commented
I’m still missing the 64x64 icon. Please check my previous comment though.

2024-03-17 18:37 UTC, Gustvst commented on discord.png
They can be put in the way I said, sorry if I expressed it poorly in this message here, I'm Brazilian and I have difficulty understanding English.

2024-03-19 01:37 UTC, Tellinq approved these changes

2024-03-19 02:08 UTC, Tellinq commented on discord.png
If you're fine with the logo as it is, go ahead and resolve this conversation. However, I would revisit this as the logo might look weird as it's not in its proper proportions at the moment

2024-03-19 02:28 UTC, Gustvst commented on discord.png
Yes

2024-03-20 00:59 UTC, Gustvst commented
Close?

2024-03-23 20:24 UTC, closed without merging